# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bda3bdda7734489f90bf916081bc09773a3f99ec2a0f8ab315ea86f2c2c135c49d56bad898ea92c1365d03d5991b32c45c33538558d60d898a1ce08f9ac0af98

test:
  secret_key_base: 66f68395a0b3f8780fa4eb404454bffe8306e8ac30c732ee34d6a54122fa4be833f1889759d27f10e2231c59d8ebae49a9325b205f9638edda6ec65b8bc2dbdb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
